[build]
  publish = "."

[functions]
  [functions.environment]
    MONGODB_URI = "mongodb+srv://saurabh:SAURABH@cluster0.4rifvig.mongodb.net/portfolio?retryWrites=true&w=majority&appName=Cluster0"
    ADMIN_PASSWORD = "admin123"
    SESSION_TOKEN = "mock-admin-session-token-omega"

[[redirects]]
  from = "/"
  to = "/home.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
